<font size=4 face='楷体'>

## Python 程序假死

Python 程序假死或无异常退出可能的原因

示例代码

```python
while True:
    try:
        ... some code ...
        time.sleep(100);
        ... other code ...
    except Exception,e:
        ... some code...
```

程序运行一段时间后, 通过日志排查发现程序在 sleep 之后不再启动运行了, 也没有报错, 处在一个假死的状态, 那么这是如何引起的呢

### 可能原因

- 内存占用过大
  代码中产生的变量随着 while 循环的生产, 导致内存过大, 栈中的变量地址不停更换, 指向内存堆中新的值, 当一定时间后, python 内存管理机制（垃圾回收机制）来不及消除未引用的值的时候, 栈的变量去寻找值的时候耗时很久或寻址假死, 此时就会引起内存过大引起的程序假死现象
- 垃圾回收机制
  程序 sleep 很久后, 原来的变量的值会可能被回收掉, 导致程序无法正确运行, 此时程序也会出现假死现象

### 解决办法

- 使用超时限制
  使用 eventlet 中的 Timeout 方法

  ```python
  import eventlet
  import time

  eventlet.monkey_patch(time=True)


  def timeout(value, _time):
      with eventlet.Timeout(_time, False):  # 设置超时间
          time.sleep(4)
          print('name为字符串类型_值是{}'.format(value))
          return 'str'
      return '不好意思函数调用超时'


  if __name__ == '__main__':
      print(timeout(8, 3))
  ```

  使用包 func_timeout, `pip install func_timeout`

  ```python
  from func_timeout import func_set_timeout
  import func_timeout


  @func_set_timeout(3)  # 设定函数超执行时间_
  def task():
      print('hello world')
      time.sleep(5)
      return '执行成功_未超时'


  if __name__ == '__main__':
      try:
          print(task())
      # 若调用函数超时自动走异常(可在异常中写超时逻辑处理)
      except func_timeout.exceptions.FunctionTimedOut:
          print('执行函数超时')
  ```

- 管理内存
  在代码中, 通过代码优化, 管理内存, 此项需要结合代码来完成, 一般获取数据可以通过迭代器等

## Reference

[python 中 sleep 引起的程序假死现象](https://zhuanlan.zhihu.com/p/358987957)

**2022.10.27**
